# Generated by Django 3.1.4 on 2020-12-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_1', models.CharField(max_length=30)),
                ('apellido_2', models.CharField(max_length=30, null=True)),
                ('fecha_de_nacimiento', models.DateField(null=True)),
                ('anotaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('midificado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
